import json
import streamlit as st

st.set_page_config(
    page_title="Control de Albaranes", page_icon="📋", layout="wide"
)

RAW_DATA = [
    {
        "tipo": "Otros",
        "proveedor": "Ecofax",
        "albaran": "78",
        "fecha": "2026-01-14",
        "periodo": "ENERO",
        "importe": 849.17,
        "iva": 178.33,
        "total": 1027.5,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "La Compagnie Des Desserts",
        "albaran": "26003245",
        "fecha": "2026-01-16",
        "periodo": "ENERO",
        "importe": 250.5,
        "iva": 25.05,
        "total": 275.55,
        "comentario": "",
    },
    {
        "tipo": "Sala",
        "proveedor": "Torrelsa SA",
        "albaran": "7940000514",
        "fecha": "2026-01-16",
        "periodo": "ENERO",
        "importe": 258.74,
        "iva": 25.87,
        "total": 284.61,
        "comentario": "",
    },
    {
        "tipo": "Extras",
        "proveedor": "Ecofax (Extra)",
        "albaran": "108",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 1007.95,
        "iva": 211.67,
        "total": 1219.62,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Fabricas Peña",
        "albaran": "260000983",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 299.25,
        "iva": 29.93,
        "total": 329.18,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Frutalis",
        "albaran": "13703",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 294.78,
        "iva": 12.0,
        "total": 306.78,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Ken foods",
        "albaran": "523850",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 77.57,
        "iva": 7.76,
        "total": 85.33,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "La Compagnie Des Desserts",
        "albaran": "AB 26000275",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": -250.5,
        "iva": -25.05,
        "total": -275.55,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "La Compagnie Des Desserts",
        "albaran": "26003762",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 264.38,
        "iva": 26.44,
        "total": 290.82,
        "comentario": "",
    },
    {
        "tipo": "Otros",
        "proveedor": "Lavin Lavanderías Industriales",
        "albaran": "190126",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 296.0,
        "iva": 62.16,
        "total": 358.16,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Palleiro Gourmet y Restauracion SL",
        "albaran": "2177",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 1114.1,
        "iva": 93.52,
        "total": 1207.62,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Panamar Panaderos SL",
        "albaran": "8003857409",
        "fecha": "2026-01-19",
        "periodo": "ENERO",
        "importe": 159.04,
        "iva": 6.36,
        "total": 165.4,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Almacen de jamones Jumi SL",
        "albaran": "26000203",
        "fecha": "2026-01-20",
        "periodo": "ENERO",
        "importe": 1125.69,
        "iva": 105.69,
        "total": 1231.38,
        "comentario": "",
    },
    {
        "tipo": "Sala",
        "proveedor": "Bodegas Bordino",
        "albaran": "2601051",
        "fecha": "2026-01-20",
        "periodo": "ENERO",
        "importe": 2584.55,
        "iva": 542.76,
        "total": 3127.31,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Corner Empresarial SL",
        "albaran": "26000509",
        "fecha": "2026-01-20",
        "periodo": "ENERO",
        "importe": 304.26,
        "iva": 30.43,
        "total": 334.69,
        "comentario": "",
    },
    {
        "tipo": "Otros",
        "proveedor": "Ecofax",
        "albaran": "114",
        "fecha": "2026-01-20",
        "periodo": "ENERO",
        "importe": 68.2,
        "iva": 14.32,
        "total": 82.52,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "La Compagnie Des Desserts",
        "albaran": "26003952",
        "fecha": "2026-01-20",
        "periodo": "ENERO",
        "importe": 176.75,
        "iva": 17.68,
        "total": 194.43,
        "comentario": "",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Almacen de jamones Jumi SL",
        "albaran": "26000273",
        "fecha": "2026-01-21",
        "periodo": "ENERO",
        "importe": 471.43,
        "iva": 47.15,
        "total": 518.58,
        "comentario": "",
    },
    {
        "tipo": "Sala",
        "proveedor": "Coca-Cola European Partners Iberia SLU",
        "albaran": "4529719394",
        "fecha": "2026-01-21",
        "periodo": "ENERO",
        "importe": 536.17,
        "iva": 110.59,
        "total": 646.76,
        "comentario": "Además 9 envases VR237 y 3 VR30",
    },
    {
        "tipo": "Sala",
        "proveedor": "Coca-Cola European Partners Iberia SLU",
        "albaran": "4529984976",
        "fecha": "2026-01-21",
        "periodo": "ENERO",
        "importe": 62.12,
        "iva": 13.05,
        "total": 75.17,
        "comentario": "ENVASES",
    },
    {
        "tipo": "Cocina",
        "proveedor": "Discarlux",
        "albaran": "26004492",
        "fecha": "2026-01-21",
        "periodo": "ENERO",
        "importe": 680.4,
        "iva": 68.04,
        "total": 748.44,
        "comentario": "",
    },
    {
        "tipo": "Extras",
        "proveedor": "Ecofax (Extra)",
        "albaran": "128",
        "fecha": "2026-01-21",
        "periodo": "ENERO",
        "importe": 346.04,
        "ivaNo me han programado para hacer algo así.
